#!/bin/bash

# Script conventional name is wallschmart_modulename
selfname=`basename "$0" | sed s/wallschmart_//`

rm -f "$selfname"_raw.html "$selfname"_ISO-8859-15.html "$selfname".html

wget -q -O "$selfname"_raw.html \
        --user-agent="User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 14.9; rv:32.0) Gecko/20150101 Firefox/32.0"  \
	http://www.meteo-paris.com

# wkhtmltoimage produces humongous files, so
# let's only let him render what we actually want
# First, don't forget the stylesheets
xmllint --encode utf-8 --html --xpath ' ( //link[@rel = "stylesheet"] )' --htmlout --format "$selfname"_raw.html 2> /dev/null > "$selfname".html
# Then select the actual data - along with the URL, this is the most important variable between modules
xmllint --encode utf-8 --html --xpath ' ( //div[@id = "prevision"] ) [1]' --htmlout --format "$selfname"_raw.html 2> /dev/null >> "$selfname".html

# Stupid wkhtmltoimage believes that relative links are local filesystem,
# so we have to absolute them before handing the HTML to him
ex -V1 "$selfname".html <<-EOF
  %s,'//,'http://,ge 
  %s,"//,"http://,ge 
  %s,'/,'http://www.meteo-paris.com/,ge
  %s,"/,"http://www.meteo-paris.com/,ge
# Also, some characters require escaping as HTML entities lest wkhtmltoimage chokes on them
  %s/’/\&#8217/g
  wq " Update changes and quit.
EOF

# By default, wkhtmltoimage expect ISO-8859-1
# 'wkhtmltoimage --encoding utf-8' should make this step unnecessary...
iconv -f UTF-8 -t ISO-8859-15 < "$selfname".html > "$selfname"_ISO-8859-15.html

# Debian's wkhtmltoimage won't run without an xserver
# so let's use xvfb-run to make him believe there is one
xvfb-run wkhtmltoimage --width 1280 --format PNG --crop-w 589 "$selfname"_ISO-8859-15.html ../../output/"$selfname".png

rm -f "$selfname"_raw.html "$selfname"_ISO-8859-15.html "$selfname".html

